- hosts: localhost
  connection: local
  vars:
    release: xenial
    user: ""
  tasks:
  - name: install dependencies packages
    apt:
      name: "{{ item }}"
      update_cache: yes
      cache_valid_time: 86400
      state: latest
    with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common

  - name: add repo key
    apt_key:
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present

  - name: add repo
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu {{ release }} stable"
      update_cache: yes

  - name: install packages
    apt:
      name: docker-ce
      state: latest

  - name: configure user
    when: user is defined and user != ""
    user:
      name: "{{ user }}"
      groups: "docker"

  - name: ensure service
    service:
      name: docker
      enabled: yes
      state: started
